import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { cn } from '@/lib/utils';

const sansation = localFont({
  src: [
    {
      path: '../fonts/Sansation-Light.ttf',
      weight: '300',
    },
    {
      path: '../fonts/Sansation-Regular.ttf',
      weight: '400',
    },
    {
      path: '../fonts/Sansation-Bold.ttf',
      weight: '700',
    },
  ],
  variable: '--font-sansation',
});

export const metadata: Metadata = {
  title: 'ЯРЕМЯ | ПРОСТІР РОСЛИН',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={cn('h-full', 'antialiased', sansation.variable)}>
      <body className='min-h-full flex flex-col'>{children}</body>
    </html>
  );
}
