import type { Metadata } from 'next';
import { Sansation } from 'next/font/google';
import './globals.css';

const sansation = Sansation({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  variable: '--font-sansation',
});

export const metadata: Metadata = {
  title: 'ЯРЕМЯ | ПРОСТІР РОСЛИН',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${sansation.variable}  h-full antialiased`}>
      <body className='min-h-full flex flex-col'>{children}</body>
    </html>
  );
}
